# These are supported funding model platforms

github: JustArchi
patreon: JustArchi
custom: ["https://www.paypal.me/JustArchi/5eur", "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HD2P2P3WGS5Y4", "https://pay.revolut.com/profile/ukaszyxm", "https://steamcommunity.com/tradeoffer/new/?partner=46697991&token=0ix2Ruv_"]
